version: '3.1'
services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin_123
      - MYSQL_DATABASE=qa_db
      - MYSQL_USER=qa
      - MYSQL_PASSWORD=user_123
    network_mode: bridge
