version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin_123
      - MYSQL_DATABASE=qa_db
      - MYSQL_USER=qa
      - MYSQL_PASSWORD=user_123
    networks:
      - mynetwork

  frontend:
    image: fake-api:latest
    container_name: fake-api-container
    ports:
      - 8001:8001
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
